### ISSUE TITLE
I think this app is broken on Android

### ISSUE THREAD

**Issue by reyco1** [PhantomAppDevelopment/pizza-app#1]
It may be the same problem that I am having... For some reason, refreshing the oauthAccessToken does not work for me anymore out of nowhere... Are you experiencing this problem?

**Comment by agentphantom** [comment]
Hi,

I noticed they changed something for the Email auth and I updated the corresponding guide.

I will take a look at this issue, maybe its the same procedure (instead of asking for a new access_token, refresh the provided one).

**Comment by reyco1** [comment]
Ok, cool... Please let me know if you discover anything new. Thanks!

**Comment by reyco1** [comment]
@agentphantom I haven't been able to crack it man... Any luck?

**Comment by reyco1** [comment]
@agentphantom the thing is that we never get a "refreshToken" from the federated login

**Comment by agentphantom** [comment]
Hi,

I have fixed it in the latest commit and I also have updated the Firebase Federated auth guide with the new instructions.

Basically you only need to add a new parameter `returnSecureToken` and the response will include a refreshToken that then it's used to get an access_token.

**Comment by reyco1** [comment]
Actually, this does not work for me... I tried your instructions to the letter and I still do not get a "refreshToken" in the response even after adding the "returnSecureToken" parameter and setting it to true. This is what my request looks like:

`private function getAccountInfo():void
        {
            var header:URLRequestHeader = new URLRequestHeader("Content-Type", "application/json");

            var myObject:Object = {};
            myObject.requestUri = requestUri;
            myObject.sessionId = sessionId;
            myObject.returnSecureToken = true;

            var request:URLRequest = new URLRequest(firebase.verifyAssertionUrl);
            request.method = URLRequestMethod.POST;
            request.data = JSON.stringify(myObject);
            request.requestHeaders.push(header);

            var loader:URLLoader = new URLLoader();
            loader.addEventListener(Event.COMPLETE, successHandler);
            loader.addEventListener(IOErrorEvent.IO_ERROR, errorHandler);
            loader.load(request);
        }`
